20230913/20230913_5th/what_the/urls.py
from django.urls import path, include
from . import views

app_name = 'what_the'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:name>', views.func, name='why_do_this')
]

20230913/20230913_5th/what_the/models.py
from django.db import models

# Create your models here.

20230913/20230913_5th/what_the/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    book_list = [
        {'author': '김시습', 'book_list': ['금오신화', '이생규장전', '만복자서포기']}, 
        {'author': '허균', 'book_list': ['홍길동전', '장생전', '도문대작']},  
        {'author': '남영로', 'book_list': ['옥루몽', '옥련몽']}, 
        {'author': '작자 미상', 'book_list': ['장화홍련전', '가락국 신화', '온달 설화']}, 
        {'author': '임제', 'book_list': ['수성지', '백호집', '원생몽유록']}
    ]
    context = {
        'book_list':book_list
    }
    return render(request, 'what_the/index.html', context)

def func(request, name):
    context = {
        'name':name
    }
    return render(request, 'what_the/fxxk.html', context)

20230913/20230913_5th/what_the/templates/what_the/fxxk.html
{% extends "base.html" %}

{% block title %}
  이걸 왜 해?
{% endblock title %}


{% block content %}
  <p>
    {{ name }}
  </p>
  
{% endblock content %}

20230913/20230913_5th/what_the/templates/what_the/index.html
{% extends "base.html" %}

{% block title %}
 이걸 왜 하죠?
{% endblock title %}


{% block content %}
  {% for books in book_list %}
    <h1>
      <a href={% url "what_the:why_do_this" books.author %}>
      {{ books.author }}
      </a>
    </h1>
      {% for book in books.book_list %}
        <ul>
          <li>{{ book }}</li>
        </ul>
        
      {% endfor %}
  {% endfor %}
{% endblock content %}