web_prac/20231017/20231017_web_4th/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

web_prac/20231017/20231017_web_4th/pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pokemon.urls')),
    path('accounts/', include('accounts.urls')),
]

web_prac/20231017/20231017_web_4th/pokemon/urls.py
from django.urls import path
from . import views

app_name = 'pokemon'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

web_prac/20231017/20231017_web_4th/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

web_prac/20231017/20231017_web_4th/pokemon/models.py
from django.db import models

# Create your models here.
class Pokemon(models.Model):
    name = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now=True)

web_prac/20231017/20231017_web_4th/pokemon/forms.py
from django import forms
from .models import Pokemon

class PokemonForm(forms.ModelForm):
    class Meta:
        model = Pokemon
        fields = '__all__'

web_prac/20231017/20231017_web_4th/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('pokemon:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('pokemon:index')

web_prac/20231017/20231017_web_4th/pokemon/views.py
from django.shortcuts import render, redirect
from .models import Pokemon
from .forms import PokemonForm

# Create your views here.
def index(request):
    pokemons = Pokemon.objects.all()
    context = {
        'pokemons':pokemons
    }
    return render(request, 'pokemon/index.html', context)

def detail(request, pk):
    pokemon = Pokemon.objects.get(pk=pk)
    context = {
        'pokemon':pokemon
    }
    return render(request, 'pokemon/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = PokemonForm(request.POST)
        if form.is_valid():
            pokemon = form.save()
            return redirect('pokemon:detail', pokemon.pk)
    else:
        form = PokemonForm()
    context = {
        'form':form
    }
    return render(request, 'pokemon/create.html', context)

def update(request, pk):
    pokemon = Pokemon.objects.get(pk=pk)
    if request.method == 'POST':
        form = PokemonForm(request.POST, instance=pokemon)
        if form.is_valid():
            form.save()
            return redirect('pokemon:detail', pokemon.pk)
    else:
        form = PokemonForm(instance=pokemon)
    context = {
        'pokemon':pokemon,
        'form':form,
    }
    return render(request, 'pokemon/update.html', context)

def delete(request, pk):
    pokemon = Pokemon.objects.get(pk=pk)
    pokemon.delete()
    return redirect('pokemon:index')

web_prac/20231017/20231017_web_4th/pokemon/templates/pokemon/create.html
{% extends "base.html" %}
{% block content %}
<h1>CREATE PAGE</h1>
<hr><hr>
<form action="{% url "pokemon:create" %}" method='POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value='새로운 포켓몬 포획을 축하합니다.'>
</form>
{% endblock content %}

web_prac/20231017/20231017_web_4th/pokemon/templates/pokemon/detail.html
{% extends "base.html" %}
{% block content %}
<h1>DETAIL PAGE</h1>
<hr><hr>
<p>포획한 순서 : {{pokemon.pk}}</p>
<p>포켓몬 이름 : {{pokemon.name}}</p>
<p>포켓몬 설명 : {{pokemon.content}}</p>
<p>포획한 시기 : {{pokemon.date}}</p>
<hr><hr>
<a href="{% url "pokemon:update" pokemon.pk%}">[UPDATE]</a>
</form>
<hr><hr>
<form action="{% url "pokemon:delete" pokemon.pk%}"method='POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value='포켓몬을 야생으로 보내주겠습니까?'>
</form>
<hr><hr>
<a href="{% url "pokemon:index" %}">[Go to the INDEX PAGE]</a>
{% endblock content %}

web_prac/20231017/20231017_web_4th/pokemon/templates/pokemon/index.html
{% extends "base.html" %}
{% block content %}
<h1>INDEX PAGE</h1>
<hr><hr>
<h3>Hello, {{user.username}}</h3>
<hr>
<hr>
<a href="{% url "accounts:login" %}">[LOGIN]</a>
<hr><hr>
<form action="{% url "accounts:logout" %}"method='POST'>
  {% csrf_token %}
  <input type="submit" value='로그아웃'>
</form>
<hr><hr>
<a href="{% url "pokemon:create" %}">[축하합니다. 새로운 포켓몬을 포획하셨습니다.]</a>
<hr><hr>
{% for pokemon in pokemons %}
<p>포획한 순서 : {{pokemon.pk}}</p>
<p>포켓몬 이름 : {{pokemon.name}}</p>
<a href="{% url "pokemon:detail" pokemon.pk%}">[More Info]</a>
<hr><hr>
{% endfor %}
{% endblock content %}

web_prac/20231017/20231017_web_4th/pokemon/templates/pokemon/update.html
{% extends "base.html" %}
{% block content %}
<h1>UPDATE PAGE</h1>
<hr><hr>
<form action="{% url "pokemon:update" pokemon.pk%}"method='POST'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value='포켓몬의 정보가 새롭게 바뀝니다.'>
  <hr><hr>
  <a href="{% url "pokemon:detail" pokemon.pk%}">[Go to the DETAIL PAGE]</a>
</form>
{% endblock content %}