web_prac/20231012/20231012_prac_2nd/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
]

web_prac/20231012/20231012_prac_2nd/app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:pk>', views.detail, name='detail'),
    # path('new/', views.new, name='new'),
    path('create', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comment/', views.comments_create, name='comments_create'),
    path('<int:app_pk>/comment/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

web_prac/20231012/20231012_prac_2nd/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_prac/20231012/20231012_prac_2nd/app/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class App(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(blank=True)
    
class Comment(models.Model):
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

web_prac/20231012/20231012_prac_2nd/app/templates/app/create.html
{% extends "base.html" %}

{% block content %}

<h1>당신 좀 하시는데요?</h1>
<hr>
<hr>
<a href="{% url "app:index" %}">[INDEX]</a>
<form action="{% url "app:create" %}" method='POST' enctype='multipart/form-data'>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock content %}

web_prac/20231012/20231012_prac_2nd/app/templates/app/detail.html
{% extends "base.html" %}

{% block content %}
  <h2>여기는 DETAIL이긴 한데...</h2>
  <p>{{ app.title }}</p>
  <hr>
  <hr>
  {% comment %} <a href="{% url "app:new" %}">[NEW]</a> {% endcomment %}

  <form action="{% url "app:delete" app.pk %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value='DELETE'>
  </form>
  <a href="{% url "app:index" %}">[back]</a>
  <hr>
  <hr>
  <a href="{% url "app:update" app.pk %}">[EDIT]</a>

  <hr>
    <h1>댓글 목록</h1>
    <ul>
      {% for comment in comments %}
        <li>
          {{comment.content}}
          <form action="{% url "app:comments_delete" app.pk comment.pk %}" method='POST'>
            {% csrf_token %}
            <input type="submit" value='delete'>
          </form>
        </li>
      {% empty %}
        <p>댓글이 없습니다.</p>
      {% endfor %}
    </ul>
    <p>{{app.comment_set.count}}</p>
    <p>{{comments|length}}</p>
    <p>{{app.comment_set.all|length}}</p>
  <hr>

  <form action="{% url "app:comments_create" app.pk %}"  method='POST'>
    {% csrf_token %}
    {{commnet_form}}
    <input type="submit">
  </form>

{% endblock content %}

web_prac/20231012/20231012_prac_2nd/app/templates/app/edit.html
{% extends "base.html" %}

{% block content %}

 {% comment %} <form action="{% url "app:update" app.pk %}" method='POST'>
  {% csrf_token %}
  <div>
    <label for="title">Title: </label>
    <input type="text" name='title' id='title' value="{{ app.title }}">
  </div>

  <div>
    <label for="content">Content: </label>
    <textarea name="content" id="content">{{ app.content }}</textarea>
  </div>
  <input type="submit">
 </form> {% endcomment %}


<h1>EDIT</h1>
<form action="{% url "app:update" app.pk %}">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

{% endblock content %}

web_prac/20231012/20231012_prac_2nd/app/templates/app/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if request.user.is_authenticated %}
  <h1>당신 로그인 되어 있는거 알고 있지?</h1>
{% else %}
  <h1>당신 로그인 안 한거 알고 있지?</h1>
{% endif %}
<hr>
<h1>로그인 하고 싶지?</h1>
<hr>
<a href="{% url "accounts:login" %}">Log In</a>
<hr>
<form action="{% url "accounts:logout" %}" method='POST'>
  {% csrf_token %}
  <input type="submit" value='Log Out'>
</form>
<hr>
  <h1>당신은 {{user.username}}</h1>
<hr>
  <a href="{% url "accounts:signup" %}">계정 만들자</a>
<hr>
  <form action="{% url "accounts:delete" %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value='회원탈퇴'>
  </form>
<hr>
  <a href="{% url "accounts:update" %}">회원정보 수정</a>
<hr>
<p><img src="{% static "app/파이리.jfif" %}" alt="파이리1"></p>
<hr>
<hr>
<p><img src="{% static "app/파이리2.jfif" %}" alt="파이리2"></p>
<hr>
<hr>
<p><img src="{% static "리자몽1.jfif" %}" alt="리자몽1"></p>
<hr>
<hr>
<p><img src="{% static "리자몽2.jfif" %}" alt="리자몽2"></p>
<hr>
<hr>
<p><img src="{% static "app/리자몽1.jfif" %}" alt="app리자몽1"></p>
<hr>
<hr>
<p><img src="{% static "app/리자몽2.jfif" %}" alt="app리자몽2"></p>
<hr>
<hr>
<a href="{% url "app:create" %}">[CREATE]</a>
  {% for app in apps %}
  
    <p>{{ app.pk }}</p>
    <p>작성자 {{app.user}}</p>
    <a href="{% url "app:detail" app.pk %}">
      <p>{{ app.title }}</p>
    </a>
    <p>{{ app.content }}</p>
    <p>{{ app.price }}</p>
    <hr>
    <hr>
    

  {% endfor %}

{% endblock content %}

web_prac/20231012/20231012_prac_2nd/app/templates/app/new.html
{% extends "base.html" %}

{% comment %} {% block content %}

  <h1>NEW</h1>
  <form action="{% url "app:create" %}" method='POST'>
    {% csrf_token %}
    <div>
      <label for="title">Title: </label>
      <input type="text" name='title' id='title'>
    </div>
    
    <div>
      <label for="content">Content: </label>
      <textarea name="content" id="content"></textarea>
    </div>

    <input type="submit">
  </form>
  <hr>
  <a href="{% url "app:index" %}">[back]</a>
{% endblock content %} {% endcomment %}

{% block content %}

<h1>NEW</h1>
<form action="{% url "app:create" %}" method='POST'>
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">

</form>

{% endblock content %}